import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json')

  return {
    props: {
      data: events_categories
    }
  }
}

export default function Home({ data }) {

  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <Image alt='placeholder'/>
          <Link href='/'>Home</Link>
          <Link href='/events'>Events</Link>
          <Link href='/about'>About us</Link>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map(ev => (
          <a key={ev.id} href={`/events/${ev.id}`}>
            <Image width={200} height={200}src={ev.image} alt={ev.id}/>
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </a>
        ))}
      </main>

      <footer className={styles.footer}>
        <h3>Im a footer</h3>
      </footer>
    </>
  )
}
